---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: dagon
# description will be included in the image's metadata
description: Personal KDE developer OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 44 # Pin the Fedora version; bump manually on new Fedora releases

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      cleanup: true
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
        - terra-bootstrap.repo
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      keys:
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      copr:
        - atim/starship
        - ublue-os/packages
    install:
      packages:
        - gh
        - code
        - brave-origin
        - starship
        - podman-compose
        - terra-release
        - terra-gpg-keys
        - ghostty
        - tailscale
        - virt-manager
        - virt-viewer
        - libvirt
        - qemu-kvm
        - edk2-ovmf
        - rocm-hip
        - rocm-opencl
        - rocm-smi
        - steam
        - fastfetch
        - input-remapper
        - krunner-bazaar
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - plasma-discover
        - plasma-discover-libs

  - type: systemd
    system:
      enabled:
        - podman.socket
        - libvirtd
        - tailscaled
        - input-remapper

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - com.heroicgameslauncher.hgl
      - scope: user # Also add Flathub user repo, but no user packages

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - NerdFontsSymbolsOnly

  - type: chezmoi
    repository: https://github.com/JackGrahn/dotfiles

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
